@startuml classDiagram

hide members

left to right direction

package factories{

  class SingletonFactoryMethod
  interface AbstractFactory <<interface>>
  class FactoryPF implements AbstractFactory
  class FactoryPJ implements AbstractFactory

  SingletonFactoryMethod --* "1" SingletonFactoryMethod : Singleton
  SingletonFactoryMethod ..> AbstractFactory
  Exception <.. SingletonFactoryMethod
  Class <.. SingletonFactoryMethod
  Object <.. SingletonFactoryMethod

}

SingletonFactoryMethod ..> pagamentos.Pagamento

package contratos{

  interface Contrato <<interface>>
  class ContratoPF implements Contrato
  class ContratoPJ implements Contrato

  FactoryPF ..> ContratoPF
  FactoryPJ ..> ContratoPJ

}

package documentos{

  interface Documento <<interface>>
  class DocmentoPF implements Documento
  class DocumentoPJ implements Documento

  FactoryPF ..> DocmentoPF
  FactoryPJ ..> DocumentoPJ

}

package pagamentos{

  interface Pagamento <<interface>>
  class PagamentoComum implements Pagamento
  abstract class PagamentoDecorator <<abstract>> implements Pagamento
  class PagamentoParcelado extends PagamentoDecorator
  class PagamentoCredito extends PagamentoDecorator
  class PagamentoDesconto extends PagamentoDecorator

  Pagamento "1" *-- PagamentoDecorator
  AbstractFactory ..> Pagamento

}

Contrato --* "1" pagamentos.Pagamento : Bridge

class Cliente

Cliente ..> AbstractFactory
Cliente --* "1" Documento
Cliente --* "1" Contrato

@enduml